version: '3'

services:
  angular:
    hostname: localhost
    build: front-angular
    ports:
      - 8080:80
    environment:
      - EXPRESS_HOST=localhost
      - EXPRESS_PORT=3000

  express:
    build: back-express
    ports:
      - "3000:3000"
    links:
      - database
    environment:
      - MONGO_DB_NAME=meandatabase
      - MONGO_PORT=27017
      - MONGO_HOST=database


  database:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-volume:/data/db

